'use strict'

const adapter = require('./adapter')
const constants = require('./internal/constants')
const regex = require('./internal/re')

module.exports = {
  parse: adapter.parse,
  valid: adapter.valid,
  clean: adapter.clean,
  inc: adapter.inc,
  diff: adapter.diff,
  major: adapter.major,
  minor: adapter.minor,
  patch: adapter.patch,
  prerelease: adapter.prerelease,
  compare: adapter.compare,
  rcompare: adapter.rcompare,
  compareLoose: adapter.compareLoose,
  compareBuild: adapter.compareBuild,
  sort: adapter.sort,
  rsort: adapter.rsort,
  gt: adapter.gt,
  lt: adapter.lt,
  eq: adapter.eq,
  neq: adapter.neq,
  gte: adapter.gte,
  lte: adapter.lte,
  cmp: adapter.cmp,
  coerce: adapter.coerce,
  truncate: adapter.truncate,
  Comparator: adapter.Comparator,
  Range: adapter.Range,
  satisfies: adapter.satisfies,
  toComparators: adapter.toComparators,
  maxSatisfying: adapter.maxSatisfying,
  minSatisfying: adapter.minSatisfying,
  minVersion: adapter.minVersion,
  validRange: adapter.validRange,
  outside: adapter.outside,
  gtr: adapter.gtr,
  ltr: adapter.ltr,
  intersects: adapter.intersects,
  simplifyRange: adapter.simplify,
  subset: adapter.subset,
  SemVer: adapter.SemVer,
  re: regex.re,
  src: regex.src,
  tokens: regex.t,
  SEMVER_SPEC_VERSION: constants.SEMVER_SPEC_VERSION,
  RELEASE_TYPES: constants.RELEASE_TYPES,
  compareIdentifiers: adapter.compareIdentifiers,
  rcompareIdentifiers: adapter.rcompareIdentifiers,
}
